spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.240/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  file:
    path: e:/workspace/javaspace/lsxspace/sell-logs
server:
  servlet:
    context-path: /sell
wechat:
  appId: 暂时没有
  appSecret: 暂时没有
